version: '2'
services:
    harry-app:
        image: harry
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://harry-mysql:3306/harry?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=harry-elasticsearch:9300
        ports:
            - 8080:8080
    harry-mysql:
        extends:
            file: mysql.yml
            service: harry-mysql
    harry-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: harry-elasticsearch
